### ISSUE TITLE
Surface support for tuples

### ISSUE THREAD

**Issue by nilehmann** [liquid-rust/flux#109]
We should have enough support for tuples in [flux-typeck](https://github.com/liquid-rust/flux/tree/main/flux-typeck), but they are not yet exposed in the surface syntax. Implementing this should require the following steps

1. Add a new `Tuple` variant to the surface syntax (https://github.com/liquid-rust/flux/blob/main/flux-syntax/src/surface.rs#L100).
1. Add code for desugaring the new variant (https://github.com/liquid-rust/flux/blob/main/flux-desugar/src/desugar.rs#L205).
1. Modify the parser to support tuples (https://github.com/liquid-rust/flux/blob/main/flux-syntax/src/surface_grammar.lalrpop). 
1. Remove the `Unit` variant from surface (https://github.com/liquid-rust/flux/blob/main/flux-syntax/src/surface.rs#L121).
1. Add some [pos](https://github.com/liquid-rust/flux/tree/main/flux-tests/tests/pos/structs) and [neg](https://github.com/liquid-rust/flux/tree/main/flux-tests/tests/neg/structs) tests, e.g.,
    ```rust
    #[flux::sig(fn((Nat, i32)) -> Nat)]
    fn test(pair: (i32, i32)) -> i32 {
        pair.0
    }
    ```
    The support in [flux-typeck](https://github.com/liquid-rust/flux/tree/main/flux-typeck) should be sufficient by now, but maybe we will find some surprices and will need to fix some bugs.

**Comment by ranjitjhala** [comment]
#![feature(register_tool)]
#![register_tool(flux)]

Another simple test that should pass when this is done:

```rust
#[flux::assume]
pub fn tuple() -> (u32, u32) {
    (10, 20)
}
```
