### ISSUE TITLE
Example wrong on front page?

### ISSUE THREAD

**Issue by chadbrewbaker** [liquid-rust/flux#112]
Doesn't i32 overflow after the max value - or am I reading the specification wrong?

**Comment by ranjitjhala** [comment]
Yes you’re correct in that the addition can overflow. As a simple default we’ve chosen to elide this important point. However for places where you really want to be sure there are no over flows, there are several ways to deal with that with refinement types, see this for example

https://ucsd-progsys.github.io/liquidhaskell-blog/2017/03/20/arithmetic-overflows.lhs/
