### ISSUE TITLE
Odd crash with polymorphic enum

### ISSUE THREAD

**Issue by ranjitjhala** [liquid-rust/flux#137]
The code below 

```rust
#![feature(register_tool)]
#![register_tool(flux)]

#[flux::refined_by(b:bool)]
pub enum Opt<T> {
    #[flux::variant(Opt<T>[false])]
    None,
    #[flux::variant(Opt<T>[true])]
    Some(T),
}

#[flux::sig(fn(Opt<i32>[true]) -> i32)]
pub fn unwrap_i32(x: Opt<i32>) -> i32 {
    match x {
        Opt::Some(v) => v,
        Opt::None => 0,
    }
}
```

panics with

```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', flux-typeck/src/type_env/paths_tree.rs:495:22
```

@nilehmann  The error is in a part of `paths_tree` I'm unfamiliar with so would be good if you can take a look!

**Comment by nilehmann** [comment]
@ranjitjhala will take a look later today.

**Comment by nilehmann** [comment]
@ranjitjhala I think I know what it is, you forgot the argument in the annotation for the Some variant. So I guess the bug is we are not reporting that error and instead just chrushing.

**Comment by ranjitjhala** [comment]
Hmm -- do you mean that it should say something like

```
#[flux::refined_by(b:bool)]
pub enum Opt<T> {
    #[flux::variant(forall T. Opt<T>[false])]
    None,
    #[flux::variant(forall T. Opt<T>[true])]
    Some(T),
}
```

**Comment by nilehmann** [comment]
No no, it should be 

```rust
#[flux::refined_by(b:bool)]
pub enum Opt<T> {
    #[flux::variant(Opt<T>[false])]
    None,
    #[flux::variant({T} -> Opt<T>[true])]
    Some(T),
}
```

**Comment by ranjitjhala** [comment]
Ugh sorry. Apparently I still haven't gotten over jet lag. Odd that the plain test passed though, I suppose because we never used the input!

**Comment by ranjitjhala** [comment]
Ok, that fixes the problem -- lets leave this open so I can revisit the "lowering" or "desugaring" phase to check the annotation is sensible.
