### ISSUE TITLE
How to write a refinement on a single variable of a struct?

### ISSUE THREAD

**Issue by cole-k** [liquid-rust/flux#154]
Ranjit asked me to post this question, although it seems rather simple (and perhaps ill-posed) to me.

I was playing around with flux and tried to extend the definition of `RangeIter` in `range.rs` to include the current index `cur`.

Original code:
https://github.com/liquid-rust/flux/blob/4e440050fe87c8edbd22271a761378eae3ca683e/flux-tests/tests/lib/range.rs#L7-L8

My change:
```rust
     #[flux::field({i32[@cur]:lo <= cur && cur <= hi})]
     cur: i32,
```

There are some other changes too, which I can post if desired.

What I ran into was an issue of not knowing how to express myself.
For the type signature of the function `next` I wanted to add an `ensures` clause that reflects the fact that in the updated `RangeIter`, the new `cur` is now either equal to `cur + 1` or `hi`.

Original code:
https://github.com/liquid-rust/flux/blob/4e440050fe87c8edbd22271a761378eae3ca683e/flux-tests/tests/lib/range.rs#L36

My attempted change:
```rust
     #[flux::sig(fn(self: &strg RngIter[@lo, @hi, @cur]) -> Option<i32{v:lo <= v && v < hi && v == cur}> ensures self: {RngIter[lo, hi, x]: x == (cur + 1) || x == hi})]
```

Flux says this is wrong because `x` is unbound, which makes sense to me. But I can't seem to figure out how to introduce an existential like it.

I can think of three explanations:
1. I don't know the right syntax.
2. The right syntax doesn't exist, but could.
3. The right syntax doesn't exist, and this shouldn't be possible.

**Comment by ranjitjhala** [comment]
Consider the spec for `RangeIter`

```rust
#[flux::refined_by(lo: int, hi: int)]
pub struct RngIter {
    #[flux::field(i32[@lo])]
    _lo: i32,
    #[flux::field(i32[@hi])]
    hi: i32,
    #[flux::field(i32{v:lo <= v && v <= hi})]
    cur: i32,
}
```

What this says is that in "refinement-land" any `RangeIter` is associated with (i.e. abstracted by) _two_ indices -- respectively `lo` and `hi` which are really the _only_ things you can talk about.

(This is _very_ different from LH...)

So when you say `RangeIter[x, y]` in some spec, it means a `RangeIter` whose `lo` index is `x` and `hi` index is `y` -- something like three params doesn't even make sense as a `RangeIter` only has _two_ indices.

If you want to talk about the exact value of `cur` for a `RangeIter` you need to also make that an index so something like

```rust
#[flux::refined_by(lo: int, cur:int, hi: int)]
pub struct RngIter {
    #[flux::field(i32[@lo])]
    _lo: i32,
    #[flux::field(i32[@hi])]
    hi: i32,
    #[flux::field({ i32[@cur]  : lo <= cur && cur <= hi })]
    cur: i32,
}
```

Now, you can write

```rust
#[flux::sig(fn(self: &strg RngIter[@lo, @cur, @hi]) -> Option<i32{v:lo <= v && v < hi && v == cur}> ensures self: STUFF )]
```

Ok, now, what to put in `STUFF` you want to say that `lo` and `hi` are as in the input, but the output is either `cur+1` or `hi` -- IF we had a `min` operator then you could have specified it with indices directly as:

```rust
ensures self: RangeIter[lo, min(cur+1, hi), hi]
```

In theory the above should be possible, at least if we add predicate aliases (LH `inline`) to `flux` and then define something like `min(x, y) = if x < y then x else y` BUT we don't have it yet. (Could be a fun exercise!)

So instead you can write the following 

```rust
ensures self: RangeIter{v: v.lo == lo && v.hi == hi && (v.cur == cur + 1 || v.cur == hi) }
```

which says, the output is a `RangeIter` indexed by `v` such that ... (the stuff in curly braces)

Btw, you can use the "dot" syntax to simplify the spec as:


```rust
#[flux::sig(fn(self: &strg RngIter[@in]) -> Option<i32{v: in.lo <= v && v < in.hi && v == in.cur}> ensures self: RangeIter{out: out.lo = in.lo && out.hi = in.hi && (out.cur = in.cur + 1 || out.cur = in.hi)})]
```

Does that make sense?

Key bit:

1. You can only talk about the indices explicitly declared in the spec
2. You can use a single index (e.g. `@in` and `out`) to refer to the whole struct, and then "dot" notation to access the values of the indices previously declared in step 1.

I haven't tried the above out on the `RangeIter` code, so it would be AWESOME if you can and update the specs accordingly and send a PR!

**Comment by nilehmann** [comment]
I'm going to close this as there's no issue to fix
