### ISSUE TITLE
Implement initial support for `BinOp::BitOr`, `BinOp::Shl` and `BinOp::Shr`

### ISSUE THREAD

**Issue by nilehmann** [liquid-rust/flux#205]
We could easily implement some basic support for these operations. For `BitOr` we should do the same as with `BitAnd` and have a refined signature for the boolean case, and an unrefined signature for the integral case. `BinOp::Shl` and `BinOp::Shr` should just have an unrefined signature for now.

**Comment by nilehmann** [comment]
A bit more mentoring. For each operator we need to:

1. Add a corresponding variant here https://github.com/liquid-rust/flux/blob/c1fb6902813ba1759f0ed55344b2155d837dfaae/flux-middle/src/rustc/mir.rs#L160
2. Lower the operator here https://github.com/liquid-rust/flux/blob/c1fb6902813ba1759f0ed55344b2155d837dfaae/flux-middle/src/rustc/lowering.rs#L407
3. Add the rule for checking the operator here https://github.com/liquid-rust/flux/blob/c1fb6902813ba1759f0ed55344b2155d837dfaae/flux-typeck/src/checker.rs#L662. This is the interesting part. The operator should be added to the `check_arith_op` case adding a suitable signature here https://github.com/liquid-rust/flux/blob/c1fb6902813ba1759f0ed55344b2155d837dfaae/flux-typeck/src/sigs.rs
4. Add pos and neg tests

**Comment by ranjitjhala** [comment]
If ultimately we want bit-level semantics -- we have to figure out what the "index" should be so we can represent in fixpoint/smtlib. IIRC SMTLIB wants different sorts
if you want to do plain `int` arith vs if you want to do bit-vector-blasting...
