### ISSUE TITLE
Implement `Rvalue::CheckedBinaryOp`

### ISSUE THREAD

**Issue by nilehmann** [liquid-rust/flux#206]
We should have enough pieces in place to implement [Rvalue::CheckedBinaryOp](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/enum.Rvalue.html#variant.CheckedBinaryOp). A mildly interesting question is what type d we give to these operations. We have a couple of options. examples using add for i32

* `fn(i32[@n], i32[@m]) -> exists b: bool. (bool[b], i32{v : b => v = n + m})`: only say something about the result if the operation didn't overflow 
* `fn(i32[@n], i32[@m]) -> (bool, i32[n + m])`: do not care about overflow

**Comment by ranjitjhala** [comment]
Seems related to #239 ? Or in general allowing for "dependent pairs" in the outputs?

**Comment by nilehmann** [comment]
Related, but we don’t strictly need it because we can give a special typing rule for checked operations, and it doesn’t need to be expressible as a function type.
