### ISSUE TITLE
Fix support for (plain) rust type aliases

### ISSUE THREAD

**Issue by ranjitjhala** [liquid-rust/flux#227]
This code is surprisingly hard to get to work with our current `resolver` pipeline.

```rust
#![feature(register_tool)]
#![register_tool(flux)]

type MyResult<T> = Result<T, ()>;

#[flux::sig(fn() -> MyResult<i32>)]
pub fn test() -> MyResult<i32> {
    Ok(10)
}
```

The trouble is that by the time we get to it, we have to resolve

* path = `MyResult` with args  = `[i32]`

with what rust has (at that point in `rustc_middle` -- NOT at `hir`) namely,

* path = `Result` with args = `[i32, ()]`

Of course we _do_ have the alias-definition (can save it in the call-chain around `insert_res_for_ident`) 
but we actually do the zipping AFTER rustc has done the expansion which makes things very tedious AFAICT.

**Comment by nilehmann** [comment]
I think the following would work:

1. Add an extra case to `surface::Res` for type aliases here https://github.com/liquid-rust/flux/blob/0dfecc33f2c209ed3936ca09472da512fb8284d3/flux-syntax/src/surface.rs#L182
2. Keep the information that it's an alias here https://github.com/liquid-rust/flux/blob/0dfecc33f2c209ed3936ca09472da512fb8284d3/flux-desugar/src/table_resolver.rs#L347
3. During `annot_check` raise an error if the alias is refined in any way (just to simplify) and use `tcx.type_of` in [`zip_path`](https://github.com/liquid-rust/flux/blob/main/flux-desugar/src/annot_check.rs#L209) to get the real type and check it is equal to the type we are zipping against.
4. During `desugaring` use `tcx.type_of` again to the get type in [`desugar_path`](https://github.com/liquid-rust/flux/blob/main/flux-desugar/src/desugar.rs#L396) and generate a type from it and raise an error if it's not supported. For that we could reuse this function https://github.com/liquid-rust/flux/blob/0dfecc33f2c209ed3936ca09472da512fb8284d3/flux-desugar/src/table_resolver.rs#L313

My hunch though is that a more elegant fix would be to do `annot_check` on `fhir` and not `surface`.

**Comment by nilehmann** [comment]
Actually, even simpler. In step 4. I think everything boils down to _follow_ the alias [here](https://github.com/liquid-rust/flux/blob/0dfecc33f2c209ed3936ca09472da512fb8284d3/flux-desugar/src/desugar.rs#L952) and [here](https://github.com/liquid-rust/flux/blob/0dfecc33f2c209ed3936ca09472da512fb8284d3/flux-desugar/src/desugar.rs#L396) raising an error if not supported, that way the alias could be refined the same as the type it alias.

**Comment by ranjitjhala** [comment]
Yes I’m trying that route but the hassle is that in step 3 you basically
have to “redo” the rustc alias expansion prior to the zipping (because the
flux sig has the alias but the rust sig is expanded…)

**Comment by nilehmann** [comment]
Yeah, step 3 is the ugly/hacky step, that we would avoid if `annot_check` was done in `fhir` instead of surface.

**Comment by nilehmann** [comment]
In any case, except for step 3, I think this is the right route. In desugaring, we need to know how a type is refined to proceed. Eventually, we want the possibility for aliases to be refined differently from the type they point to, so having the information that some path is an alias during desugaring is a step in the right direction.

**Comment by ranjitjhala** [comment]
Ok let me continue (I had already started along this and was at 3) -- btw
the hir route sounds appealing but won't work
if (or rather, when) we want to slap signatures onto imported functions
from other crates...

**Comment by nilehmann** [comment]
I finally got into studying how prusti does extern specs and they use a pretty clever trick that we should probably copy. If we use their trick then none of this would matter. It involves using procedural macros which would take some time to set up but once we do all of our problems will be solved.

**Comment by ranjitjhala** [comment]
We don’t have any api for “subst” in the flux types yes? Otherwise the way
to do 3 is to “lower” a version of the alias def to flux, apply the subst
to get the expanded sig and then zip…

**Comment by nilehmann** [comment]
oh yeah yikes, I think now I'm seeing the problem. I don't see an easy route. we could get the hir type alias definition (https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/hir/enum.ItemKind.html#variant.TyAlias) and then convert from `hir::ty` to `rustc_middle::ty` (https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir_analysis/collect/struct.ItemCtxt.html and https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir_analysis/astconv/trait.AstConv.html) but that sounds gross. I really do think the solution is to move `annot_check` to [`fhir`](https://github.com/liquid-rust/flux/blob/main/flux-middle/src/fhir.rs)

**Comment by ranjitjhala** [comment]
Will moving to fhir solve the main issue though ? Ultimately I think we
have to reimplement some form of the rustc expansion, no?

**Comment by nilehmann** [comment]
yeah, we would have to reimplement the rustc expansion anyways but that would happen during desugaring into `fhir`. In `fhir`, since we don't have aliases anymore, we could do `annot_check` against the `rustc:Ty`. What doing `annot_check` in `fhir` fixes is not doing the expansion twice.

**Comment by nilehmann** [comment]
More generally I've been thinking about how we support aliases for types with abstract refinements. Consider,

```rust
#[flux::refined_by(a: int, b: int, p: (int, int) -> bool)]
struct Pair {
    #[flux::field(i32[@a])]
    fst: i32,
    #[flux::field(i32[@b])]
    snd: i32,
}
```

Now, obviously, you don't want to spell out `p` explicitly every time you want talk about OrderedPairs, for example, but you may want to talk about `a` and `b`, so you would want something like:

```rust
#[flux::alias(type OrderedPair[a, b] = Pair[@a, @b, |a, b| a < b)]
type OrderedPair = Pair;
```

Now the question becomes, how we desugar uses of `OrderedPair`. I was thinking that during desugaring we could treat `OrderedPair` as a type on its own right with a separated `refined_by` (`a: int, b: int`) so the following uses would work

 ```rust
  fn(pair: OrderedPair[@a, @b]) -> i32[a]

  desugars to 
  
  fn<a0: int, a1: int>(Pair[a0, a1, |a2, a3| a2 < a3) -> i32[a0];
```

```rust
fn(pair: OrderedPair) -> i32[pair.a] 

desugars to

fn<a0: int, a1: int>(Pair[a0, a1, |a2, a3| a2 < a3) -> i32[a0];
```

This would require having the alias during desugaring.

note: desugaring this `fn(OrderedPair{v: v.a == v.b})` would be fun because it requires the existential to be _partially_ applied

**Comment by nilehmann** [comment]
This was fixed in https://github.com/liquid-rust/flux/pull/350
