### ISSUE TITLE
Parse error with nested types

### ISSUE THREAD

**Issue by ranjitjhala** [liquid-rust/flux#258]
The following triggers a parse error

```rust
#[flux::sig(fn () -> Option<Option<i32>>)]
pub fn foo() -> Option<Option<i32>> {
    None
}
```

but e.g. adding some random index makes it parse

```rust

#[flux::sig(fn () -> Option<Option<i32>[]>)]
pub fn foo() -> Option<Option<i32>> {
    None
}

```

**Comment by ranjitjhala** [comment]
Hmm looks like this has been around a while.

http://goto.ucsd.edu:8091/index.html#?demo=permalink%2F1671562719_503.rs

Perhaps to do with the `Comma` combinator? one can hack it by adding a junk `,` at the end like so, but rather gross...

```rust
#[flux::sig(fn () -> Option<Option<i32>,>)]
pub fn foo() -> Option<Option<i32>> {
    None
}
```

**Comment by ranjitjhala** [comment]
Aargh... adding a blank works too, so probably some strange lexer oddness.

```rust
#[flux::sig(fn() -> Option< Option<usize> >)]
```

**Comment by nilehmann** [comment]
Yeah, this has been there for a while. `>>` is tokenized as a single token. One possible solution is to split it into two tokens and put it back together when parsing a right shift operator. Not sure if lalrpop has support for this.

**Comment by ranjitjhala** [comment]
Why doesn’t this happen for left shift? Is that not a token?

**Comment by nilehmann** [comment]
`<<` is also tokenized as a single token, but there's never (lexical) ambiguity for two `<`'s, they always have to be parsed as a left shift.
