### ISSUE TITLE
Add support for `?` in calls

### ISSUE THREAD

**Issue by ranjitjhala** [liquid-rust/flux#260]
Currently the following code fails with

```rust
#![feature(register_tool)]
#![register_tool(flux)]

#[flux::sig(fn() -> Result<i32[0], ()>)]
fn baz() -> Result<i32, ()> {
    Ok(0)
}

#[flux::sig(fn() -> Result<i32[1], ()>)]
pub fn baz_call() -> Result<i32, ()> {
    let r = baz()?;
    Ok(r + 1)
}
```

which fails with

```
error[FLUX]: unsupported type in function call
    --> flux-tests/tests/pos/surface/result00.rs:11:13
     |
11   |     let r = baz()?;
     |             ^^^^^^
     |
note: function defined here
    --> /Users/rjhala/.rustup/toolchains/nightly-2022-11-07-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:2091:5
     |
2091 |     fn branch(self) -> ControlFlow<Self::Residual, Self::Output> {
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     = note: unsupported type `<std::result::Result<T, E> as std::ops::Try>::Residual`

error: aborting due to previous error
```

**Comment by ranjitjhala** [comment]
Apparently that type not yet handled is a [`Projection`](https://doc.rust-lang.org/beta/nightly-rustc/rustc_type_ir/sty/enum.TyKind.html#variant.Projection)

**Comment by nilehmann** [comment]
I've been thinking about type projections in the background and I believe what we should do is normalize the function type (maybe using this function https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.TyCtxt.html#method.type_op_normalize_poly_fn_sig). If normalize is what I think it is then `<std::result::Result<T, E>> as std::ops::Try>::Residual` should normalize to `Result<Infallible, E>`.

**Comment by nilehmann** [comment]
Another example that uses type projections

```rust
// a normal `Vec`
fn sum(v: Vec<i32>) -> i32 {
    let mut sum = 0;
    for x in v {  // calls IntoIterator::into_iter
        sum += x;
    }
    sum
}
```

**Comment by ranjitjhala** [comment]
Sounds good - I tried a different one - normalize_erasing_regions but
that didn't work (maybe because we need a better ParamEnv?) anyways let me
try this!

**Comment by nilehmann** [comment]
Yeah, we need to generate the `ParamEnv` for the particular function call somehow.

**Comment by ranjitjhala** [comment]
The plot thickens -- I came upon this: [`lower_instance`](https://github.com/liquid-rust/flux/blob/ae45d5bef7af4eee64be3308de71f0c065ccfd4a/flux-middle/src/rustc/lowering.rs#L287-L295)  which seems to have some good stuff in it.
