### ISSUE TITLE
Separate namespaces for constants and uifs

### ISSUE THREAD

**Issue by ranjitjhala** [liquid-rust/flux#323]
**Name clash in qualifiers**: we could make constants leave in a different _namespace_, i.e., define a new `newtype_index!` for them. And while we are at it maybe we should unify constants and uif. Just realized that we could also have name clashes with uifs too because they can have an arbitrary name so if someone names on `a0`, `a1`, ... we will have a clash.

_Originally posted by @nilehmann in https://github.com/liquid-rust/flux/pull/322#pullrequestreview-1246038740_

**Comment by cole-k** [comment]
Resolved by https://github.com/liquid-rust/flux/pull/380
