### ISSUE TITLE
Mutable field updates?

### ISSUE THREAD

**Issue by ranjitjhala** [liquid-rust/flux#334]
(reposted from slack)

Does `flux` currently support mutable field updates, e.g. I'm trying to work on this:
https://github.com/liquid-rust/examples/tree/kani-vec-deque/kani-vecdeque
and each of these four lines causes some sort of crash

1. [expected leaf node](https://github.com/liquid-rust/examples/blob/kani-vec-deque/kani-vecdeque/src/cve.rs#L216)
2. [expected leaf node](https://github.com/liquid-rust/examples/blob/kani-vec-deque/kani-vecdeque/src/cve.rs#L224)

3. [unknown error](https://github.com/liquid-rust/examples/blob/kani-vec-deque/kani-vecdeque/src/cve.rs#L218)
4. [unknown error](https://github.com/liquid-rust/examples/blob/kani-vec-deque/kani-vecdeque/src/cve.rs#L226)

The first two are totally baffling to me: I haven't seen that particular crash before. 

The second two are perhaps due to mutable field updates?

**Comment by ranjitjhala** [comment]
@nilehmann here's another puzzler

https://github.com/liquid-rust/examples/blob/kani-vec-deque/kani-vecdeque/src/cve.rs#L552

I get an odd "cannot split type" error at that field lookup.

Probably has to do with the preceding "join" due to the branch? (If I remove the guard and just _always_ call `self.grow()` I don't get the error...

**Comment by nilehmann** [comment]
@ranjitjhala I'm preparing a fix for that last one. Just trying to come up with a minimal test to reproduce it.

**Comment by ranjitjhala** [comment]
thanks!

**Comment by ranjitjhala** [comment]
Ah nice, this fix #335 *also* handles the mysterious "cannot split type" error, so am closing!

**Comment by ranjitjhala** [comment]
oh wait, the thing where I have to convert

```rust
self.wrap_sub(self.tail, 1);
```

to 

```rust
let tail = self.tail;
self.wrap_sub(tail, 1);
```

still doesn't work: should I keep this open then?

**Comment by nilehmann** [comment]
Yeah, I'm going to reopen because of that
