### ISSUE TITLE
Const bug

### ISSUE THREAD

**Issue by ranjitjhala** [liquid-rust/flux#338]
There is something odd going on with the translation of `const` into the fixpoint query.

The following code:

```rust

#![feature(register_tool)]
#![register_tool(flux)]

#[flux::constant]
const INITIAL_CAPACITY: usize = 7; // 2^3 - 1

#[flux::constant]
const MAXIMUM_ZST_CAPACITY: usize = 1 << (usize::BITS - 1); // Largest possible power of two

#[flux::sig(fn (n: usize{n < MAXIMUM_ZST_CAPACITY}))]
fn foo(n: usize) {}

pub fn bar() {
    foo(INITIAL_CAPACITY)
}
```

generates the smt2 file

```smt2
(constraint
  (forall ((_ Unit) (a1 = -9223372036854775808))
    (forall ((_ Unit) (a0 = 7))
      (tag (7 < a1) "0")
    )
  )
)
```

(which is rejected of course...)

**Comment by ranjitjhala** [comment]
@nilehmann -- the bug is here 

https://github.com/liquid-rust/flux/blob/main/flux-driver/src/collector.rs#L154

the output is wrong, here is the before / after conversion

```
TRACE: parse_const_spec: DefId(0:5 ~ const03[a2df]::MAXIMUM_ZST_CAPACITY) = 0x8000000000000000
TRACE: parse_const_spec: DefId(0:5 ~ const03[a2df]::MAXIMUM_ZST_CAPACITY) = -9223372036854775808
``` 

any idea on what the best fix is?

**Comment by ranjitjhala** [comment]
Is the problem that `ScalarInt` is a u128 that we are trying to crunch into `i128`?

https://doc.rust-lang.org/beta/nightly-rustc/rustc_middle/ty/struct.ScalarInt.html

**Comment by nilehmann** [comment]
@ranjitjhala yeah, `ScalarInt::try_to_int` will just interpret the bits as an `i128`. We should look at the type of the `const` to determine how to actually interpret the bits.

**Comment by nilehmann** [comment]
we use similar logic here https://github.com/liquid-rust/flux/blob/f0ebc50e43f8a096fd12ba2b411e60ca4c4952fe/flux-middle/src/rustc/lowering.rs#L738

**Comment by ranjitjhala** [comment]
aha, nice -- why not use this same `Constant` type in the `const_map` ?

**Comment by nilehmann** [comment]
@ranjitjhala that sounds sensible.
